config/routes.rb
Lovelyio::Application.routes.draw do
  VERSION_RE = /\d+\.\d+\.\d+(-[a-z0-9]+)?/i

  get '/users/:user_id/packages(/search/:search)(/page/:page)' => 'packages#index', :as => :user_packages
  get '/tags/:tag/(/search/:search)(/page/:page)'              => 'packages#index', :as => :tagged_packages
  get '/packages(/search/:search)(/page/:page)'                => 'packages#index'


  resources :packages, :only => [:index, :show, :create, :destroy] do
    collection do
      get :recent,  :action => :index, :order => 'recent'
      get :updated, :action => :index, :order => 'updated'
    end
  end

  get '/packages/:id/changelog'                 => 'packages#changelog', :as => :package_changelog
  get '/packages/:id(/:version)/demo'           => 'packages#demo',      :as => :package_demo,      :constraints => { :version => VERSION_RE }
  get '/packages/:id(/:version)'                => 'packages#show',      :as => :package,           :constraints => { :version => VERSION_RE }
  get '/packages/:id(/:version)/docs(/:doc_id)' => 'packages#docs',      :as => :package_docs,      :constraints => {
    :version => VERSION_RE, :doc_id => /[a-z0-9\-_\.\/]+/
  }

  resources :users
  resource  :profile, :controller => 'users' do
    get :token
  end

  get '/news(/page/:page)' => 'news#index'
  resources :shows, :path => 'show'
  resources :news


  # authentication routes
  match '/login'                   => 'sessions#new',     :as => :login
  match '/logout'                  => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback' => 'sessions#create'   # omniauth callback
  match '/auth/failure'            => 'sessions#create'   # omniauth failures

  # CDN urls
  get '/:id(-:version).js' => "static#script", :as => :cdn_package, :format => 'js', :constraints => {
    :version => VERSION_RE
  }
  get '/:id(/:version)/:path' => "static#image", :as => :cdn_image, :constraints => {
    :version => VERSION_RE, :path => /[\w\d\/\-\_\._]+\.(gif|png|jpg|jpeg|svg|swf|eot|ttf|woff)/i
  }
  get '/assets/:sha' => "static#sha", :as => :cdn_asset

  # static pages
  get '/:id' => "static#page", :as => :page

  root :to => "static#page", :id => 'index'

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :packages, :order => :name, :foreign_key => :owner_id

  attr_accessible :email, :name, :home_url

  validates_presence_of :provider, :uid, :name
  validates_format_of :email, :with => /^[\w\d\.\-]+@[\w\d\.\-]+$/, :allow_blank => true
  validate :provider_and_uid_uniqueness, :on => :create

  # find or create a user by omni-auth data-hash
  def self.find_or_create_by_auth(auth)
    find_by_provider_and_uid(auth['provider'], auth['uid']) ||
    create! do |user|
      user.uid        = auth['uid']
      user.provider   = auth['provider']
      user.name       = auth['info']['name']
      user.location   = auth['info']['location']
      user.avatar_url = auth['info']['image']
      user.home_url   = case auth['provider']
        when 'github'   then "http://github.com/#{auth['info']['nickname']}"
        when 'twitter'  then "http://twitter.com/#{auth['info']['nickname']}"
        when 'facebook' then "http://www.facebook.com/profile.php?id=#{auth['uid']}"
        else nil
      end
    end
  end

  def self.find_by_auth_token(token)
    id, token = token.split('$')
    if user = User.find_by_id(id)
      if BCrypt::Password.new(user.auth_token) == token
        return user
      end
    end

  # in case the hash was not set yet
  rescue BCrypt::Errors::InvalidHash
    return nil
  end

  AUTH_TOKEN_SIZE    = 64
  AUTH_TOKEN_SYMBOLS = ('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a

  def new_auth_token!
    token = AUTH_TOKEN_SYMBOLS.shuffle!.slice(0, AUTH_TOKEN_SIZE).join('')
    self.auth_token = BCrypt::Password.create(token).to_s
    self.save
    "#{id}$#{token}"
  end

  def admin?
    'admin' == role
  end

private

  def provider_and_uid_uniqueness
    if self.class.find_by_provider_and_uid(provider, uid)
      self.errors.add(:uid, "is already taken for this provider")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :except => [:show, :new, :create, :destroy]
  before_filter :require_admin, :only   => :index
  before_filter :find_user,     :except => :index
  before_filter :check_access,  :only   => [:edit, :update]

  def index
    @users = User.order('name')
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile was successfully updated"
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def token
    @token = @user.new_auth_token! if params[:create]
  end

  # blocking the rest of the REST
  def new()     raise NotFound end
  def create()  raise NotFound end
  def destroy() raise NotFound end

protected

  def find_user
    @user = if request.fullpath.starts_with?(profile_path)
      raise AccessDenied if !logged_in?
      current_user
    else
      User.find(params[:id])
    end
  end

  def check_access
    raise AccessDenied if !admin? and @user != current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    image_tag user.avatar_url, :class => :avatar
  end

  def user_avatar_link(user)
    link_to user_avatar(user), user
  end
end

app/views/users/edit.html.haml
%h1 Edit profile

= form_for @user, :url => profile_path do |f|
  = f.error_messages

  %p.required
    = f.label :name
    = f.text_field :name

  %p.required
    = f.label :email
    = f.text_field :email

  %p
    = f.label :home_url
    = f.text_field :home_url

  %p.buttons
    = f.submit 'Save'

%p.bottom-links
  = link_to "Back", profile_path, :class => :back

app/views/users/index.html.haml
%h1 Users Index

%p Will be here shortly

app/views/users/show.html.haml
%h1 Profile details

.avatar-block
  = user_avatar_link @user

%dl.profile
  %dt Full name
  %dd= @user.name

  %dt Home url
  %dd= link_to @user.home_url, @user.home_url unless @user.home_url.blank?

  %dt Packages
  %dd= link_to "packages by this user", user_packages_path(@user)

  - if @user == current_user
    %dt Email
    %dd= @user.email

    %dt Authentication Token
    %dd= link_to "Create new auth-token", token_profile_path

%p.bottom-links
  - if logged_in?
    = link_to "Edit", edit_profile_path, :class => :edit

app/views/users/token.html.haml
%h1 Authentication Token Generator

%p
  Authentication tokens are used with the <tt>lovely</tt> console tool
  when you deploy your packages to <tt>lovely.io</tt>




- if @token
  %h2 New Token

  %p
    Please add the following to your <tt>~/.lovelyrc</tt> file

  %pre= "auth = #{@token}"

  %p
    = link_to "Make a new one", token_profile_path(:create => true)

- else
  %h2 Generate A Token

  %p
    Click the following link to generate a new authentication-token

  %p
    <b>NOTE:</b> will make the current token invalid!

  %p
    = link_to "Got it! Make me a new one!", token_profile_path(:create => true)