config/routes.rb
Lovelyio::Application.routes.draw do
  VERSION_RE = /\d+\.\d+\.\d+(-[a-z0-9]+)?/i

  get '/users/:user_id/packages(/search/:search)(/page/:page)' => 'packages#index', :as => :user_packages
  get '/tags/:tag/(/search/:search)(/page/:page)'              => 'packages#index', :as => :tagged_packages
  get '/packages(/search/:search)(/page/:page)'                => 'packages#index'


  resources :packages, :only => [:index, :show, :create, :destroy] do
    collection do
      get :recent,  :action => :index, :order => 'recent'
      get :updated, :action => :index, :order => 'updated'
    end
  end

  get '/packages/:id/changelog'                 => 'packages#changelog', :as => :package_changelog
  get '/packages/:id(/:version)/demo'           => 'packages#demo',      :as => :package_demo,      :constraints => { :version => VERSION_RE }
  get '/packages/:id(/:version)'                => 'packages#show',      :as => :package,           :constraints => { :version => VERSION_RE }
  get '/packages/:id(/:version)/docs(/:doc_id)' => 'packages#docs',      :as => :package_docs,      :constraints => {
    :version => VERSION_RE, :doc_id => /[a-z0-9\-_\.\/]+/
  }

  resources :users
  resource  :profile, :controller => 'users' do
    get :token
  end

  get '/news(/page/:page)' => 'news#index'
  resources :shows, :path => 'show'
  resources :news


  # authentication routes
  match '/login'                   => 'sessions#new',     :as => :login
  match '/logout'                  => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback' => 'sessions#create'   # omniauth callback
  match '/auth/failure'            => 'sessions#create'   # omniauth failures

  # CDN urls
  get '/:id(-:version).js' => "static#script", :as => :cdn_package, :format => 'js', :constraints => {
    :version => VERSION_RE
  }
  get '/:id(/:version)/:path' => "static#image", :as => :cdn_image, :constraints => {
    :version => VERSION_RE, :path => /[\w\d\/\-\_\._]+\.(gif|png|jpg|jpeg|svg|swf|eot|ttf|woff)/i
  }
  get '/assets/:sha' => "static#sha", :as => :cdn_asset

  # static pages
  get '/:id' => "static#page", :as => :page

  root :to => "static#page", :id => 'index'

end

app/views/pages/404.html.haml
%h1 404 Error

%p
  The page you're looking for does not exists

app/views/pages/422.html.haml
%h1 422 Error

%p
  You don't have access to this part of the site

app/views/pages/about.html.haml
%h1 About Project

%p
  <tt>Lovely.IO</tt> is a front-side development platform, which includes
  a modular framework, development tools, CDN hosting, packaging and
  asynchronous modules loading with automatic dependencies handling.

%p
  The idea of the project is to provide a full-stack environment for
  creating easy to maintain and use front-side modules. In a sense it
  is much like server-side languages package managers, but for
  the front side.

%h1 Contacts

%dl
  %dt Google Group
  %dd= link_to "Lovely.IO Google Group", "http://groups.google.com/group/lovelyio"

  %dt IRC Channel
  %dd= link_to "#lovelyio on freenode", "irc://irc.freenode.net/lovelyio"

  %dt Follow me on Twitter!
  %dd= link_to "@nemshilov", "http://twitter.com/nemshilov"

  %dt Bug Trackers
  %dd
    %li= link_to "Core issues", "https://github.com/lovely-io/lovely.io-stl/issues"
    %li= link_to "Site issues", "https://github.com/lovely-io/lovely.io-host/issues"

app/views/pages/benchmark.html.haml
%h1 DOM Speed Benchmark

%p
  <b>Disclamer:</b> this benchmark uses the #{link_to "kick-ass package", package_path("kick-ass")}
  to test the library's performance. All source code of the test is available at the
  <a href="https://github.com/MadRabbit/kick-ass">package's GitHub repo</a>.

%p
  #start
    %a{"href" => "#"} <b>Start The Test!</b>

%p
  #test-container

:javascript
  Lovely(["kick-ass-1.0.0", "dom"], function(KickAss, $) {
    var test = new KickAss({
      libs: [
        'lovely-1.4.3',
        'jquery-1.9.1',
        'jquery-2.0.0'
      ]
    });

    test.insertTo('#test-container');

    test.on('finish', function() {
      $('#start').hide();
    });

    $(document).delegate('#start', 'click', function(e) {
      e.preventDefault();
      this.first('a') && test.start();
      this.html('Working...');
    });
  });

app/views/pages/index.html.haml
.punch-line
  .half-width
    %h1 Forget The Installation!

    %p
      Lovely.IO is a centralized repository of front-side packages

    %p
      Just say which packages you need and you'll get them!

  .half-width
    %pre{:"data-lang" => "html"}
      :preserve
        &lt;script src="http://cdn.lovely.io/core.js"&gt;&lt;/script&gt;
        &lt;script type="text/javascript"&gt;
          Lovely(['dom', 'ajax', 'fx'], function($, Ajax, Fx) {
            // you're ready to rock!
          });
        &lt;/script&gt;


.punch-line
  .half-width
    %pre{:"data-lang" => "js"}
      :preserve
        Lovely(['mines-game-1.0.2'], function(MinesGame) {
          var game = new MinesGame();
          game.insertTo(document.body);
        });

  .half-width
    %h1 Forget Dependencies!

    %p
      Lovely.IO automatically #{ link_to "resolves all the dependencies", package_demo_path('mines-game')} for you!


.punch-line
  .half-width
    %h1 Forget The Assets Hassle!

    %p
      Lovely.IO #{ link_to "automatically handles all the assets", package_demo_path('ui')}.

    %p
      All styles, images, etc. They're just there!

  .half-width
    %pre{:"data-lang" => "js"}
      :preserve
        Lovely(['ui-2.3.4'], function(UI) {
          var icon = new UI.Icon('delete');
          icon.insertTo('#my-element');

          // all styles are already there!
        });

.punch-line
  .half-width
    %a.thmb{:href => "/images/pages/landing-benchmark.png", :"data-zoom" => ""}<
      %img{:src => "/images/pages/landing-benchmark-thmb.png", :style => "height: 7em;"}

    :javascript
      Lovely(['zoom'], function() {});

  .half-width
    %h1 Enjoy The DOM Speed!

    %p
      Lovely.IO DOM package is build on a new architecture

    %p
      It uses dom-wrappers, which are #{link_to "much, much faster!", "/benchmark"}

.punch-line
  .half-width
    %h1 Enjoy The Loading Speed!

    %p
      Lovely.IO is build upon AMD structure

    %p
      And it uses CloudFront for #{link_to "fast packages delivery!", "/loading-test"}

  .half-width
    %a.thmb{:href => "/images/pages/landing-loading.png", :"data-zoom" => ""}<
      %img{:src => "/images/pages/landing-loading.png", :style => "height: 7em;"}

.punch-line
  .half-width
    %pre{:"data-lang" => 'coffee'}
      :preserve
        LoginForm = Form.inherit
          send: ->
            @$super() if @valid()

          valid: ->
            @values()['username'] && @values()['password']

  .half-width
    %h1 Be Civilized On Front-Side!

    %p
      Lovely.IO uses OOP dom-wrappers at it's core

    %p
      Which allows you to write clean and maintanable code


.punch-line
  .half-width
    %h1 Be Part Of It!

    %p
      Lovely.IO is an open and fully automated repository

    %p
      Anyone can share #{link_to "their packages", user_path(User.first)} in here!

  .half-width#installation-example
    %pre{:"data-lang" => "shell", :"data-colorifier" => '{"gutter": false}'}
      :preserve
        $ npm install lovely -g
        $
        $ lovely new my-awesome-package
        $ cd my-awesome-package
        $ ...
        $ lovely publish



.packages-block
  .half-width
    %h2 New Packages

    .packages
      - Package.recent.limit(10).each do |package|
        = render package

    %p.bottom-links
      = link_to "All packages", packages_path

  .half-width
    %h2 Updated Packages

    .packages
      - Package.updated.limit(10).each do |package|
        = render package

    %p.bottom-links
      = link_to "RSS Feed", updated_packages_path(:format => :atom)

app/views/pages/live.html.erb
<h1>Live Demo</h1>

<div id="live-demo">

<textarea id="demo-code">
Lovely(['dom', 'fx'], function($) {
  $('#test')
    .html('Hello World!')
    .highlight('pink');
});
</textarea>
<button id="reset">Reset</button>
<button id="start">Try Me!</button>


<div id="test"></div>

</div>

app/views/pages/loading-test.html.haml
%h1 Content Delivery Speed Test

%p
  <b>Disclamer:</b> Lovely.IO is AMD based and loads 4 files by using the following layout

%pre.lovely-io{:"data-lang" => "html"}
  :preserve
    &lt;html>
      &lt;head>
        &lt;script src="http://cdn.lovely.io/core-1.4.1.js">&lt;/script>
        &lt;script>
          Lovely(['dom-1.4.3', 'ajax-1.1.4', 'fx-1.1.1'], function() {});
        &lt;/script>
      &lt;/head>
    &lt;/html>

%p
  For jQuery delivery we use the googleapis hosting with the following layout

%pre.jquery{:"data-lang" => "html"}
  :preserve
    &lt;html>
      &lt;head>
        &lt;script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js">&lt;/script>
      &lt;/head>
    &lt;/html>

%p
  #frames-container
  #results-container
    .result
      %h2 Lovely
      %ul.lovely

    .result
      %h2 jQuery
      %ul.jquery

%p
  #start
    %a{"href" => "#"} <b>Start The Test!</b>
    %span{"style" => 'opacity: 0.7'} (don't forget to clean up the browser's cache first!)


:css
  #frames-container {
    position: absolute;
    top: -20em;
  }
  #results-container .result {
    display: inline-block;
    vertical-align: top;
    width:   20em;
  }

:javascript
  Lovely(['dom'], function($) {
    $(document).delegate('#start', 'click', function(e) {
      e.preventDefault();

      if (!this.find('a')) return;

      this.html('Working...');

      $('#frames-container').html(
        '<iframe src="test/load-lovely.html"></iframe>' +
        '<iframe src="test/load-jquery.html"></iframe>'
      );

      this.hide();
    });

    window.loading_log = function(lib, what, time) {
      $('#results-container ul.'+ lib).append(
        "<li>"+ what + " in: " + time + "ms</li>"
      );
    }
  });

app/views/pages/terms.html.haml
%h1 Terms Of Use

%p
  <a href="http://lovely.io">Lovely.IO</a> project and its packages registry are
  owned by Nikolay Nemshilov. All rights not explicitly granted in the MIT license
  are reserved.

%p
  The packages that hosted on the <a href="http://lovely.io">lovely.io</a> service
  are not part of the <a href="http://lovely.io">lovely.io</a> project itself, but
  solely property and responsibility of their maintainers.

%p
  Packages that are published on <a href="http://lovely.io">lovely.io</a> are not
  affiliated or endorsed by the <a href="http://lovely.io">lovely.io</a> project or
  Nikolay Nemshilov

%p
  While all efforts are made to ensure accountability, there is no guaranty of any
  kind, warrantee, or assertion made to the quality, or lack of malice in the
  <a href="http://lovely.io">lovely.io</a> service or any given package hosted on it.


%h2 Use Of Service

%ol
  %li
    You are granted a non-exclusive, non-transferable license to use the
    <a href="http://lovely.io">lovely.io</a> service as a source of publicly
    available packages, and also as a hosting platform for your own modules.

  %li
    By using any of the packages hosted at this service, you therefore confirm
    that you are agree with the current terms of use and with the package's
    license agreement.

  %li
    By publishing a package at the <a href="http://lovely.io">lovely.io</a>
    service you confirm that you are agree with the current terms of use and
    allow the third party applications use your module in terms of your
    package's license agreement

  %li
    You are free to choose your own license for your own packages.



%h2 Restrictions Of Use

%ol
  %li
    The <a href="http://lovely.io">lovely.io</a> service shall not be used to host
    any sort of offensive or dangerous content and/or spyware.

  %li
    The <a href="http://lovely.io">lovely.io</a> cannot be used to host any other
    general use frameworks that duplicate the STL packages functionality.

  %li
    No packages hosted at <a href="http://lovely.io">lovely.io</a> should provide
    an explicit support of obsolete browsers and browsers that do not comply with
    the W3C standards.

  %li
    All packages hosted at <a href="http://lovely.io">lovely.io</a> should not
    copy, reverse engineer and such, any commercial projects that are protected by
    copyright law and explicitly prohibit other developers from doing so.


%h2 Administrative Actions

%ol
  %li
    Administration of the <a href="http://lovely.io">lovely.io</a> service reserves
    the right to block or/and remove any user or package from the service without
    an explicit explanation or prior warning.

  %li
    Administration of this service reserves the right to change the terms of service
    at any time and in any way that appears to be suitable to the administration.