config/routes.rb
Lovelyio::Application.routes.draw do
  VERSION_RE = /\d+\.\d+\.\d+(-[a-z0-9]+)?/i

  get '/users/:user_id/packages(/search/:search)(/page/:page)' => 'packages#index', :as => :user_packages
  get '/tags/:tag/(/search/:search)(/page/:page)'              => 'packages#index', :as => :tagged_packages
  get '/packages(/search/:search)(/page/:page)'                => 'packages#index'


  resources :packages, :only => [:index, :show, :create, :destroy] do
    collection do
      get :recent,  :action => :index, :order => 'recent'
      get :updated, :action => :index, :order => 'updated'
    end
  end

  get '/packages/:id/changelog'                 => 'packages#changelog', :as => :package_changelog
  get '/packages/:id(/:version)/demo'           => 'packages#demo',      :as => :package_demo,      :constraints => { :version => VERSION_RE }
  get '/packages/:id(/:version)'                => 'packages#show',      :as => :package,           :constraints => { :version => VERSION_RE }
  get '/packages/:id(/:version)/docs(/:doc_id)' => 'packages#docs',      :as => :package_docs,      :constraints => {
    :version => VERSION_RE, :doc_id => /[a-z0-9\-_\.\/]+/
  }

  resources :users
  resource  :profile, :controller => 'users' do
    get :token
  end

  get '/news(/page/:page)' => 'news#index'
  resources :shows, :path => 'show'
  resources :news


  # authentication routes
  match '/login'                   => 'sessions#new',     :as => :login
  match '/logout'                  => 'sessions#destroy', :as => :logout
  match '/auth/:provider/callback' => 'sessions#create'   # omniauth callback
  match '/auth/failure'            => 'sessions#create'   # omniauth failures

  # CDN urls
  get '/:id(-:version).js' => "static#script", :as => :cdn_package, :format => 'js', :constraints => {
    :version => VERSION_RE
  }
  get '/:id(/:version)/:path' => "static#image", :as => :cdn_image, :constraints => {
    :version => VERSION_RE, :path => /[\w\d\/\-\_\._]+\.(gif|png|jpg|jpeg|svg|swf|eot|ttf|woff)/i
  }
  get '/assets/:sha' => "static#sha", :as => :cdn_asset

  # static pages
  get '/:id' => "static#page", :as => :page

  root :to => "static#page", :id => 'index'

end

app/views/layouts/_search.html.haml
%form#search{:action => packages_path + "/search", :method => :get}
  %input{ :type => 'text', :placeholder => "Search", :name => :search, :value => params[:search]}

app/views/layouts/_userbar.html.haml
= link_to "Profile", profile_path, :id => 'profile'
= link_to "Log In",  login_path,   :id => 'login'

app/views/layouts/application.html.haml
!!!HTML5
%html
  %head
    - main_content = yield
    - sidebar_content = yield(:sidebar)
    - @page_title ||= (main_content.scan(/<h1>(.+?)<\/h1>/im)[0] or [''])[0]
    - @page_title = 'Home' if @page_title.blank?
    - @page_title = @page_title.gsub(/<[^>]+>/, '')

    %title= "Lovely.IO » #{@page_title}"
    %meta{ :charset => "utf-8" }
    = stylesheet_link_tag    'application'
    = javascript_include_cdn 'core', 'dom', 'colorifier'
    = javascript_include_tag 'application'
    = yield :head

    = auto_discovery_link_tag :atom, news_index_path(:format => :atom), :title => "Lovely.IO News"
    = auto_discovery_link_tag :atom, updated_packages_path(:format => :atom), :title => "Lovely.IO Packages"

  %body{:class => body_class_name}
    %header
      %h1= link_to 'Lovely.IO', '/'
      %h2 The Next Generation of Front-Side

      = render 'layouts/search'

      %nav
        = link_to "Packages", packages_path
        |
        = link_to "Demo!", page_path('live'), :class => "live"
        |
        = link_to "TV Show", shows_path
        |
        = link_to "News", news_index_path
        |
        = link_to "Wiki", "http://github.com/lovely-io/lovely.io-stl/wiki"
        |
        = render 'layouts/userbar'



    - unless sidebar_content.blank?
      %sidebar= sidebar_content

    %section
      = main_content
      .clear

    %footer
      Copyright (C) 2011-2013
      = link_to "Nikolay Nemshilov", "http://nikolay.theosom.com"

      %nav
        = link_to "Terms of Use", page_path(:terms)
        |
        = link_to "About", page_path(:about)